try {
    // code ...
}catch(err){
    // error handeling
}